# For Jekyll SEO
title: Singapore Government Design System
description: >-
  Design System unites Singapore Government digital services around a common visual language 
  and user experience
logo: /assets/img/logo_sgds.png

# Site data
sgds-version: 1.3.17
report_vulnerability: "https://tech.gov.sg/report_vulnerability"
contact_us: "https://form.gov.sg/forms/govtech/5bc440ac507956000fdbae91"
feedback_form: "https://form.gov.sg/#!/forms/govtech/5bd12c6668dbe7000fff9ace"
search_placeholder: "What are you looking for?"

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

collections_dir: collections
collections:
  standard:
    permalink: /components/:path/
    output: true
    order: 1
  general:
    permalink: /components/:path/
    output: true
    order: 3
  form:
    permalink: /components/:path/
    output: true
    order: 4
  guides:
    permalink: /guides/:path/
    output: true
  get-started:
    permalink: /get-started/:path/
    output: true
  utilities:
    permalink: /utilities/:path/
    output: true
  patterns:
    permalink: /patterns/:path/
    output: true

exclude:
  - apps/src
  - node_modules
  - build
  - scripts
  - Dockerfile
  - Gemfile*
  - package*.json
  - README.md
  - webpack.config.js
  - Gruntfile.js
  - amplify.yml

sass:
  sass_dir: assets/custom-css
